### ISSUE TITLE
difficulty following demo-launch instructions

### ISSUE THREAD

**Issue by mitchellsundt** [OpenLMIS/openlmis-blue#2]
I get a 404 when I try to access http://localhost/public

However, if I access the consul console (port 8500) I see everything is active.
![consul-broken-demo](https://cloud.githubusercontent.com/assets/2281171/21737468/bfc8f164-d42d-11e6-9b4d-ebe71fd5d0f2.png)

Is there a missing step to launch the UI for these services?

**Comment by joshzamor** [comment]
@mitchellsundt : Sorry, you were bitten by some stale doc.  Just drop the /public and let me know if that works.

**Comment by mitchellsundt** [comment]
Better. I get a lot of label.app.header, label.app.sign.in etc.

Is there a language pack or file I need to configure to point at?

**Comment by mitchellsundt** [comment]
Also not sure what is available to navigate to after I log in. I just get a blank home screen:
![blank-homescreen](https://cloud.githubusercontent.com/assets/2281171/21737844/b99d2b58-d431-11e6-9ab2-3e002f75017e.png)

**Comment by joshzamor** [comment]
You shouldn't have to configure a language pack.  Try refreshing/clearing your browser cache.  If that doesn't do it a screenshot should help.

The README is a bit confusing in how it describes the users that are available v. the ones your should use to see a demo.  In short, use the demo data account `administrator` instead of the bootstrap account `admin`.

**Comment by mitchellsundt** [comment]
Here's the login screen on a cleared browser. Seems like if no language is chosen (1st use), then there is no defaulting to, e.g., English, or having some way to choose a language.
![no-label-translations](https://cloud.githubusercontent.com/assets/2281171/21737989/ee4092da-d433-11e6-8742-654aa5b1bec3.png)

Logging in as administrator does give more tab options on the home screen.

**Comment by mitchellsundt** [comment]
And I've confirmed that if I log out of the home screen, I do then see the English translations on this screen. It is only on 1st use with a cleared browser cache.

**Comment by joshzamor** [comment]
Would you happen to have a FireFox version available to test with that as well.  I can reproduce with Chrome but not FireFox atm.

**Comment by mitchellsundt** [comment]
Happens there as well. 
![no-label-translations-firefox](https://cloud.githubusercontent.com/assets/2281171/21738131/67e57e1a-d435-11e6-85a2-e2812def00e5.png)

When I click on the change-language labels, they all give errors except English, and then when I refresh after selecting English, then the dialog shows the appropriate English text.

**Comment by joshzamor** [comment]
Thanks for reporting it @mitchellsundt.  I've just found that a similar/same issue was filed the other day:  https://openlmis.atlassian.net/browse/OLMIS-1610

I've appended to that ticket that it appears to not be limited to Chrome when on Linux.

Should we close this issue?

**Comment by mitchellsundt** [comment]
Closed.
